name: Change Requests Counter

on:
  pull_request_review:
    types: [submitted]
  
jobs:
  process-jira-event:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Count Change Request
        id: list-files
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}
          echo "Extracted PR number: $PR_NUMBER"
          
          diff_url="https://api.github.com/repos/${{ github.repository }}/pulls/${PR_NUMBER}/reviews"
          echo "$diff_url"  # Debugging line
          change_requests=$(curl -s "$diff_url" | jq 'map(select(.state == "CHANGES_REQUESTED")) | length')
          echo "::set-output name=change_requests::$change_requests"
          echo "Change Requests: $change_requests"

          code_changes=$(curl -s "${diff_url}files" | jq '[.[] | .additions] | add')
          echo "Code Changes: $code_changes"
          echo "::set-output name=change_requests::$change_requests"
          echo "::set-output name=code_changes::$code_changes"


