name: Cypress Tests

on:
  workflow_dispatch: # Manually trigger the workflow

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
    
      - name: Install node and cache dependencies
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "npm"

      # Install npm dependencies from the cypress directory
      - name: Install Dependencies
        run: npm install

      # Run Cypress test for specific file
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          spec: cypress/e2e/customerEnvironment/highLevelTestCases.cy.js
