name: Cypress Tests

on:
  workflow_dispatch: # Manually trigger the workflow

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
    
      - name: Install node and cache dependencies
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "npm"

      # Install npm dependencies from the cypress directory
      - name: Install Dependencies
        run: npm install

      # Update cypress.config.js with new values
      - name: Update Cypress config
        run: |
          sed -i 's#baseURL: "http://localhost:4200"#baseURL: "https://awsportal.vultara.com"#' cypress.config.js
          sed -i 's#apiURL: "http://localhost:4201/api"#apiURL: "https://awsportal.api.vultara.com/api"#' cypress.config.js
          sed -i 's#authURL: "http://localhost:4202/auth"#authURL: "https://awsportal.auth.vultara.com/auth"#' cypress.config.js
          sed -i 's#username: "vultara_automation_test"#username: "shoaibadmin"#' cypress.config.js
          sed -i 's#password: "tJVJhiHmlIWR"#password: "PAKistan@123"#' cypress.config.js
          
          BASE_URL=$(awk -F'"' '/baseURL/{print $4}' cypress.config.js)
          echo "::set-output name=base-url::$BASE_URL"
      # Run Cypress test for specific file
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          spec: cypress/e2e/customerEnvironment/highLevelTestCases.cy.js
