name: Automation Testing Parallel

on:
  pull_request:
    branches:
      - main

jobs:
  prepare:
    if: "!contains(github.event.pull_request.labels.*.name, 'skip testing')"
    runs-on: ubuntu-latest
    outputs:
      integration-tests: ${{ steps.parse.outputs.integration-tests }}
    steps:
      - name: Say hello
        run: echo "successfully completed"
